### PR TITLE
Enable KaTeX behind an option flag

### PR DESCRIPTION
**Pull request by andrewwhitehead**

### CODE REVIEW

**Comment by andrewwhitehead** [comment]
@csuwildcat Any thoughts? This is for a new spec at https://github.com/decentralized-identity/revocation

**Comment by csuwildcat** [comment]
I like what you're doing here, but can we make sure the assets (JS) being used are not linking to external endpoint, and instead that they are baked into the page inline?

**Comment by swcurran** [comment]
@andrewwhitehead @csuwildcat -- what is the status of this PR?  We could really use the ability to have Latex in our spec.  Is this required for that?

Thanks!

**Comment by csuwildcat** [comment]
Yeah, this would probably do it, but I was asking that we have the CSS bundled inline so specs can render without dependency on some outside site to serve the styles.

**Comment by swcurran** [comment]
Another request for completing this.  Sorry I'm not sure what is needed, or I would do it.

**Comment by andrewwhitehead** [comment]
Updated now so that the `katex` flag is specified in the spec definition. When enabled, the fonts directory is copied from the katex package and would need to be distributed along with index.html.

**Comment by swcurran** [comment]
Another of weekly pings for @csuwildcat about this.  Are you happy with what Andrew has done?  Enough to merge this PR?  This would be a big a help for spec. writers.

Thanks

**Comment by brianorwhatever** [comment]
this looks like it has the files baked in and not external now. can you take a look @csuwildcat?

**Comment by swcurran** [comment]
@csuwildcat --please review and (if appropriate) merge this PR.

**Comment by csuwildcat** [comment]
Ok, looking today to make sure the external file dependency part was corrected, will merge if so.

**Comment by swcurran** [comment]
You were so close yesterday, @csuwildcat.  Maybe today?

**Comment by csuwildcat** [comment]
@swcurran @andrewwhitehead was there any way to reuse the mechanism that the other files are being pulled from based on entries added to this file mapping object?: https://github.com/decentralized-identity/spec-up/blob/master/src/asset-map.json. I ask because I see fetching code and special asset grabbing code that I would hope doesn't need duplication. If the one I have that pulls on the other assets can't work, could it be made to grab the KaTeX assets with some modification?

**Comment by csuwildcat** [comment]
Here's where that mapping object is digested and used to pull in the assets is lists: https://github.com/decentralized-identity/spec-up/blob/master/gulpfile.js#L30-L50. The map is basically just file paths grouped by type and location of injection, which the Gulp runner grabs, compresses, and minifies to insert at either the head or end of body, depending on where you need it.

**Comment by andrewwhitehead** [comment]
@csuwildcat I believe the JS and CSS can be added to the current asset groups instead of being included with this method, but that wouldn't allow for optional inclusion (processing the document with KaTeX could still be optional). The KaTeX assets are already minified so I don't imagine the document size would be much different.

**Comment by swcurran** [comment]
@andrewwhitehead -- can you please resolve the conflicts?
@csuwildcat -- once resolved, can this please, please be merged?  We could really use this feature.

**Comment by brianorwhatever** [comment]
Looks like the changes have been made and this is ready to merge @csuwildcat

**Comment by swcurran** [comment]
Go  @csuwildcat  Go!!!

**Comment by swcurran** [comment]
Yay!

**Comment by csuwildcat** [comment]
I'll probably refactor to make these kinds of things abstract and more pluggable in a future release, but my failure to find the time these last few months shouldn't block you.

**Pull request merged**
