### PR TITLE
External Specification References

### LINKED ISSUE #56: Cannot include references of RFCs above RFC8910
For some reason, spec-up does not render any IETF RFCs above RFC8910.

Do you have to publish a new version of spec-up to support this?

### PR DESCRIPTION
**Pull request by brianorwhatever**
- Adds a log during render if there are any unused defs or unresolved refs
- Allows an `external_specs` list option in the spec config that is a name/value object where the value is a URL of an external (spec-up) specification
- Creates a new `x-ref` tag to use external spec references `[[x-ref: {name}, {ref}]]` where `{name}` is from above external_specs and `{ref}` is the definition within the specification that is being referred to

It also closes #56

### CODE REVIEW

**Comment by csuwildcat** [comment]
I'll take a look at this over the weekend, thanks for the contribution!

**Comment by brianorwhatever** [comment]
Awesome, thanks!

**Comment by csuwildcat** [comment]
My only question is does the code try to do external fetch upon every watched change when editing, or is it caching at all? Just wouldn't want render to freeze up based on unavailable external resources when editing or building via automated means.

**Comment by darrellodonnell** [comment]
any chance we can get this PR approved? @csuwildcat

**Comment by csuwildcat** [comment]
@darrellodonnell will do now!

**Comment by csuwildcat** [comment]
@brianorwhatever would it be possible to resolve those conflicts? They shouldn't be anything big, I think it's just the auto-gen'd HTML and the lock via the recent dependency update.

**Comment by csuwildcat** [comment]
I will be sure to merge right after, I didn't see that last update of yours until just now.

**Comment by brianorwhatever** [comment]
@csuwildcat done!

**Pull request merged**
